# Generated by Django 4.2.3 on 2023-10-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='employee',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
