# Generated by Django 4.2.3 on 2024-01-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0002_membership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='membership',
            table='membership',
        ),
    ]
