# Generated by Django 4.2.3 on 2023-10-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0002_rename_name_user_employee_user_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='employee',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
    ]
