# Generated by Django 4.2.3 on 2024-01-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0003_alter_membership_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='user',
            new_name='user_id',
        ),
    ]
