# Generated by Django 4.2.3 on 2023-10-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0003_rename_employee_user_name_remove_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.CharField(default='example@email.com', max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='login', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=15),
        ),
    ]
