# Generated by Django 4.2.3 on 2023-10-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0004_remove_user_name_user_email_address_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(default='vbzdcn', max_length=25, unique=True),
        ),
    ]
