# Generated by Django 4.2.3 on 2024-01-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0004_rename_group_membership_group_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='user_id',
            new_name='user',
        ),
    ]
