# Generated by Django 4.2.3 on 2024-01-27 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_view', '0005_rename_group_id_membership_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportgroups',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
