# Generated by Django 4.2.3 on 2023-10-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0005_alter_user_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
