# Generated by Django 4.2.3 on 2024-01-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_view', '0007_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='sportGroups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
