# Generated by Django 4.2.6 on 2024-01-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportgroups',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sportgroups',
            name='group_name',
        ),
        migrations.AddField(
            model_name='sportgroups',
            name='discipline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='sportgroups',
            table='sportGroups',
        ),
    ]
