# Generated by Django 4.2.3 on 2024-01-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0009_rename_description_sportgroups_trainer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportgroups',
            name='actual_size',
        ),
        migrations.RemoveField(
            model_name='sportgroups',
            name='max_size',
        ),
        migrations.RemoveField(
            model_name='sportgroups',
            name='trainer_name',
        ),
    ]
