# Generated by Django 4.2.3 on 2024-01-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0010_remove_sportgroups_actual_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportgroups',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
