# Generated by Django 4.2.3 on 2024-01-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0011_alter_sportgroups_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportgroups',
            name='id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
