# Generated by Django 4.2.3 on 2024-01-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0012_alter_sportgroups_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportgroups',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
