# Generated by Django 4.2.3 on 2024-01-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0014_sportgroups_actual_size_sportgroups_max_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportgroups',
            name='actual_size',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sportgroups',
            name='max_size',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
