# Generated by Django 4.2.3 on 2024-01-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0018_alter_sportgroups_trainer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportgroups',
            name='trainer_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
