# Generated by Django 4.2.6 on 2024-01-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_view', '0009_remove_sportgroups_description_and_more'),
        ('main_view', '0020_alter_sportgroups_trainer_name'),
    ]

    operations = [
    ]
